apiVersion: batch/v1
kind: Job
metadata:
  name: siege-job
spec:
  template:
    spec:
      containers:
      - name: siege
        image: yokogawa/siege:latest
        args: ["-c30", "-t10S", "http://10.100.59.27:8888"]  # Example IP and port
      restartPolicy: Never
