apiVersion: v1
kind: Service
metadata:
  name: tensorflow-service
spec:
  type: ClusterIP  # This is the default type, which exposes the service on a cluster-internal IP.
  ports:
    - port: 8888  # The port that the service will be exposed on inside the cluster.
      targetPort: 8888  # The port on the pod that the service should route to.
  selector:
    app: tensorflow  # This should match the labels of the pods you want to expose.
