apiVersion: v1
kind: Service
metadata:
  name: tensorflow-service
spec:
  type: NodePort
  ports:
    - port: 8888
      targetPort: 8888
      nodePort: 30088  # Optional: specify a port or leave it out to have Kubernetes assign one
  selector:
    app: tensorflow
