apiVersion: apps/v1
kind: Deployment
metadata:
  name: tensorflow
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tensorflow
  template:
    metadata:
      labels:
        app: tensorflow
    spec:
      containers:
      - name: tensorflow
        image: tensorflow/tensorflow:latest
        ports:
        - containerPort: 8080
        command: ["sh", "-c"]
        args: [
          "echo '<html><body><h1>Hello TensorFlow</h1></body></html>' > /usr/share/html/index.html && \
          cd /usr/share/html && \
          python3 -m http.server 8080"
        ]
        volumeMounts:
        - name: html-volume
          mountPath: /usr/share/html
      volumes:
      - name: html-volume
        emptyDir: {}
