apiVersion: apps/v1
kind: Deployment
metadata:
  name: tensorflow
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tensorflow
  template:
    metadata:
      labels:
        app: tensorflow
    spec:
      containers:
      - name: tensorflow
        image: tensorflow/tensorflow:latest
        ports:
        - containerPort: 8080
        command: ["sh", "-c"]
        args: [
          "echo '<!DOCTYPE html><html><head><style>body { display: flex; justify-content: center; align-items: center; height: 100vh; margin: 0; font-family: Arial, sans-serif; background-color: #B2FE67; position: relative; } #content { text-align: center; } input[type=text], button { margin-top: 20px; padding: 10px; width: 350px; font-size: 16px; height: 50px; box-sizing: border-box; } #message { margin-top: 20px; color: #555; } footer { position: fixed; bottom: 0; width: 100%; text-align: center; margin: 10px 0; font-size: 14px; } </style></head><body><div id=\"content\"><h1>SysdigGPT</h1><form id=\"queryForm\"><input type=\"text\" placeholder=\"Ask me anything about AI Security\" name=\"userQuery\"><button type=\"submit\">Submit</button><div id=\"message\"></div></form></div><footer>Built for fun by <b>Nigel Douglas</b></footer><script>document.getElementById('queryForm').onsubmit = function(event) { event.preventDefault(); const userQuery = document.querySelector('[name=\"userQuery\"]').value; fetch('/api/submit', { method: 'POST', headers: {'Content-Type': 'application/json'}, body: JSON.stringify({ query: userQuery }) }).then(response => response.json()).then(data => { console.log(data); }).catch(error => { console.error('Error:', error); }); }; </script></body></html>' > /usr/share/html/index.html && \
          cd /usr/share/html && \
          python3 -m http.server 8080"
        ]
        volumeMounts:
        - name: html-volume
          mountPath: /usr/share/html
      volumes:
      - name: html-volume
        emptyDir: {}
