apiVersion: v1
kind: Service
metadata:
  name: tensorflow-service
spec:
  type: LoadBalancer
  ports:
  - port: 8888
    targetPort: 8888
    name: jupyter
  - port: 8080
    targetPort: 8080
    name: http
  selector:
    app: tensorflow
